### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by heryartshtv** [wow-company/calculator-builder#1]
does it support each field can use different colors? and is it possible to add a hide field feature on the front so that something doesn't need to appear.

**Comment by wow-company** [comment]
We can add these option in the new version of the plugin. We will try to do it soon

**Comment by heryartshtv** [comment]
> 
> 
> We can add these option in the new version of the plugin. We will try to do it soon

thank you very much admin, these plugins are very good. really helped me make a calculator.
If allowed, can you add a list and text separator without fields?

**Comment by wow-company** [comment]
> > We can add these option in the new version of the plugin. We will try to do it soon
> 
> thank you very much admin, these plugins are very good. really helped me make a calculator.
> If allowed, can you add a list and text separator without fields?

Sorry, but what do you mean about 'list'? Do you want do add list of the text?

**Comment by heryartshtv** [comment]
sorry if my english is not good.
i mean added separator line, and text

**Comment by heryartshtv** [comment]
thnks for adding feature sir :)
